config/routes.rb
Rails.application.routes.draw do

  resources :listings do
    resources :images, only: [:create, :destroy]
    resources :bookings
    member do
      get 'listing'
      get 'price'
      get 'description'
      get 'photo'
      get 'amenity'
      get 'location'
      get 'check_current_bookings'
      get 'review_booking'
    end
  end

  
  get 'users/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users, only: [:show]

  get 'static_page/index'
  get 'search' => 'searches#search'

  root  'static_pages#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_many :images
  has_many :bookings, dependent: :destroy 

  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :fetch_listing, except: [:new, :create, :index]

  def index
    @listings = Listing.where(users_id: current_user).paginate(page: params[:page], per_page: 10)
    
  end

  def show
    @listing = Listing.find(params[:id])
  end

  def new
    @listing = Listing.new
  end
  
  def create
    @listing = Listing.create(listing_params)
    if @listing.save
      flash[:success] = "Successfully Created !!"
      redirect_to listing_listing_path(@listing)
    else
      flash[:danger] = @listing.errors.full_messages.to_sentence #this will return the full message for the errors "Please input content"
      redirect_back(fallback_location: request.referer)
    end
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update(listing_params)
      flash[:success] = "Listing updated !!"
    else
      flash[:alert] = @listing.errors.full_messages.to_sentence
    end
    redirect_back(fallback_location: root_path)
  end

  def destroy
    Listing.find(params[:id]).destroy
    redirect_to listings_path
  end

  def listing
  end

  def photo
    @images = @listing.images
  end

  def description
  end

  def price
  end

  def amenity
  end

  def location
  end

  def address
    [street, city, state, country].compact.join(', ')
  end

  def check_current_bookings
    today = Date.today
    booking = @listing.bookings.where("check_in_date >= ? OR check_out_date >= ?", today, today)

    render json: booking
  end

  def review_booking
    check_in_date = Date.parse(params[:check_in_date])
    check_out_date = Date.parse(params[:check_out_date])

    result = { conflict: check_conflicts(check_in_date, check_out_date, @listing) }

    render json: result
  end

  private
  def listing_params
    params.require(:listing).permit(
      :users_id,
      :listing_name,
      :home_type,
      :room_type,
      :price,
      :accomodate,
      :bedroom_count,
      :bathroom_count,
      :listing_description,
      :has_internet,
      :has_tv,
      :has_kitchen,
      :has_heating,
      :has_air_conditioner,
      :address,
      :is_active
    )
  end

  def fetch_listing
    @listing = Listing.find(params[:id])
  end

  def check_conflicts(check_in_date, check_out_date, listing)
    check = @listing.bookings.where('? < check_in_date AND check_out_date < ?', check_in_date, check_out_date)
    check.size > 0 ? true : false
  end
end

app/helpers/listings_helper.rb
module ListingsHelper

  def is_filled?(entry)
    if entry.present?
      content_tag :i, nil, class: 'fa fa-check text-success'
    else
      content_tag :i, nil, class: 'fa fa-times text-danger'
    end
  end

  def is_ready_to_publish(listing)
    listing.address.present? && listing.listing_description.present? && listing.price.present? && listing.listing_name.present? && listing.images.present?
  end

end

app/views/listings/_sidebar.html.erb
<table class="table table-bordered">
    <tbody>
        <tr>
        <td><%= link_to "Listing", listing_listing_path, class: "mr-auto" %></td><td class="text-center"><%= is_filled?(@listing) %></td>
        </tr>
        <tr>
        <td><%= link_to "Price", price_listing_path, class: "mr-auto" %></td><td class="text-center"><%= is_filled?(@listing.price) %></td>
        </tr>
        <tr>
        <td><%= link_to "Description", description_listing_path, class: "mr-auto" %></td><td class="text-center"><%= is_filled?(@listing.listing_description) %></td>
        </tr>
        <tr>
        <td><%= link_to "Photo", photo_listing_path, class: "mr-auto" %></td><td class="text-center"><%= is_filled?(@listing.images) %></td>
        </tr>
        <tr>
        <td><%= link_to "Amenity", amenity_listing_path, class: "mr-auto" %></td><td class="text-center"><i class="fa fa-check text-success"></i></td>
        </tr>
        <tr>
        <td><%= link_to "Location", location_listing_path, class: "mr-auto" %></td><td class="text-center"><%= is_filled?(@listing.address) %></td>
        </tr>
    </tbody>
</table>

<hr>

<%= form_for(@listing) do |f| %>
    <%= f.hidden_field :is_active ,value: true %>
    <%= f.submit "Publish", disabled: !is_ready_to_publish(@listing), class: "btn btn-success w-100 mb-3" %>
<% end %>

<%= link_to "View Listing", listing_path, class: "btn btn-primary w-100" %>

app/views/listings/amenity.html.erb
<div class="row">
    <div class="col-3">
        <%= render 'sidebar' %>
    </div>

    <div class="col-9">
        <div class="card">
            <div class="card-header">
                Amenities
            </div>
            <div class="card-body">
                <%= form_for(@listing) do |f| %>
                    <div class="row">
                        <div class="col-4">
                            <%= f.check_box :has_internet %>
                            <%= f.label :has_internet, "WiFi & Internet" %>
                        </div>
                        <div class="col-4">
                            <%= f.check_box :has_tv %>
                            <%= f.label :has_tv, "TV" %>
                        </div>
                        <div class="col-4">
                            <%= f.check_box :has_kitchen %>
                            <%= f.label :has_kitchen, "Kitchen" %>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            <%= f.check_box :has_heating %>
                            <%= f.label :has_heating, "Heating" %>
                        </div>
                        <div class="col-4">
                            <%= f.check_box :has_air_conditioner %>
                            <%= f.label :has_air_conditioner, "Air Conditioner" %>
                        </div>
                        
                    </div>

                    <%= f.submit "Save", class: "btn btn-block btn-success mt-3"%>
                <% end %>
            </div>
        </div>
    </div>

</div>

app/views/listings/description.html.erb
<div class="row">
    <div class="col-3">
        <%= render 'sidebar' %>
    </div>

    <div class="col-9">
        <div class="card">
            <div class="card-header">
                Description
            </div>
            <div class="card-body">
                <%= form_for(@listing) do |f| %>
                    
                    <%= f.label :listing_name %><%= f.text_field :listing_name, class: "form-control" %>
                      
                    <%= f.label :listing_description , class: "mt-3" %><%= f.text_field :listing_description, class: "form-control" %>

                    <%= f.submit "Save", class: "btn btn-block btn-success mt-3"%>
                    
                <% end %>
            </div>
        </div>
    </div>

</div>

app/views/listings/index.html.erb
<%= provide(:title,"Your Listings")%>

<div class="row">
    <div class="col-2">
        <%= link_to "Manage Listings", listings_path, class: "btn btn-outline-primary mr-3 w-100" %>
        <button type="button" class="btn btn-outline-primary mr-3 w-100 my-3">Your Reservation</button>
        <button type="button" class="btn btn-outline-primary mr-3 w-100">Go Trip</button>
    </div>

    <div class="col-10">
        <div class="row">
            <div class="col-6">
                 <h2>Your Listings</h2>
            </div>
            <div class="offset-3">
                <%= link_to raw("Add a new Listings <i class='fa fa-pen'></i>") , new_listing_path ,class: "btn btn-primary" %>
            </div>
        </div>
        <div class="row">
            <table class="table table-hover mt-3">
                <thead class="text-center">
                    <tr>
                        <th scope="col">Image</th>
                        <th scope="col">Listing name</th>
                        <th scope="col">Price</th>
                        <th scope="col">Review</th>
                        <th colspan="3">Action</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    <% @listings.each do |listing| %>
                        <tr>
                            <% if listing.images.present? %>
                                <td><%= image_tag listing.images.first.image, style: "width: 100px; height: 100px;" %></td>
                            <% else %> 
                                <td>No images</td>
                            <% end %>
                            <td><%= listing.listing_name %></td>
                            <td><%= listing.price %></td>
                            <td></td>
                            <td><%= link_to raw(" <i class='fas fa-poo fa-rotate-90'></i> View Listing"), listing_path(listing), class: "text-primary" %></td>
                            <td><%= link_to raw("<i class='fas fa-edit'></i> edit"), listing_listing_path(listing), class:"text-info" %></td>
                            <td><%= link_to raw("<i class='fas fa-trash-alt'></i> Delete"), listing_path(listing),method: :delete,data: { confirm: "Are you sure?" }, class:"text-danger" %></td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
            <%= will_paginate(@listings) %>
        </div>
    </div>

</div>


    

app/views/listings/listing.html.erb
<div class="row">
    <div class="col-3">
        <%= render 'sidebar' %>
    </div>

    <div class="col-9">
        <div class="card">
            <div class="card-header">
                Listing
            </div>
            <div class="card-body">
                <%= form_for(@listing) do |f| %>
            <div class="row">
                <div class="col-6">Home type<%= f.select :home_type, options_for_select([
                                ["Condominium"],
                                ["Resort"],
                                ["Hotel"],
                                ["Beach House"], 
                                ["Apartment"],
                                ["Capsule Room"]
                            ]), {}, class: "form-control" %>
                </div>
                <div class="col-6">Room type<%= f.select :room_type, options_for_select([
                                ["Entire"],
                                ["Private"],
                                ["Shared"]
                            ]), {}, class: "form-control" %>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-4">Accommodate<%= f.select :accomodate, options_for_select([
                                ["1 Guest", 1],
                                ["2 Guests", 2],
                                ["3 Guests", 3],
                                ["4+ Guests", 4]
                            ]), {}, class: "form-control" %>
                </div>
                <div class="col-4">Bedroom<%= f.select :bedroom_count, options_for_select([
                                ["1 Bedroom", 1],
                                ["2 Bedrooms", 2],
                                ["3 Bedrooms", 3],
                                ["4+ Bedrooms", 4]
                            ]), {}, class: "form-control" %>
                </div>
                <div class="col-4">Bathroom<%= f.select :bathroom_count, options_for_select([
                                ["1 Bathroom", 1],
                                ["2 Bathrooms", 2],
                                ["3 Bathrooms", 3],
                                ["4+ Bathrooms", 4]
                            ]), {}, class: "form-control" %>
                </div>
            </div>
            <%= f.submit "Save", class: "btn btn-block btn-success mt-3"%>
        <% end %>
            </div>
        </div>
    </div>

</div>

app/views/listings/location.html.erb
<div class="row">
    <div class="col-3">
        <%= render 'sidebar' %>
    </div>

    <div class="col-9">
        <div class="card">
            <div class="card-header">
                Location
            </div>
            <div class="card-body">
                <%= form_for(@listing) do |f| %>
                        <%= f.label :address, "Address" %>
                        <%= f.text_field :address, class: "form-control", placeholder: "What's the address" %>
                        
                        <%= f.submit "Save", class: "btn btn-block btn-success mt-3"%>
                <% end %>
            </div>
        </div>
    </div>

</div>

app/views/listings/new.html.erb
<div class="card">
    <div class="card-header">
        Create your beautiful place
    </div>
    <div class="card-body">
        <%= form_for(@listing) do |f| %>
            <div class="row">
                <%= f.hidden_field :users_id, value: current_user.id %>
                <div class="col-4"><%= f.label :listing_name, "Property Name" %><%= f.text_field :listing_name, class: "form-control",required:true %>
                </div>
                <div class="col-4"><%= f.label :home_type, "Home type" %>
                <%= f.select :home_type, options_for_select([
                                ["Condominium"],
                                ["Resort"],
                                ["Hotel"],
                                ["Beach House"], 
                                ["Apartment"],
                                ["Capsule Room"]
                            ]), {}, class: "form-control" %>
                </div>
                <div class="col-4">Room type<%= f.select :room_type, options_for_select([
                                ["Entire"],
                                ["Private"],
                                ["Shared"]
                            ]), {}, class: "form-control" %>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col-4">Accommodate<%= f.select :accomodate, options_for_select([
                                ["1 Guest", 1],
                                ["2 Guests", 2],
                                ["3 Guests", 3],
                                ["4+ Guests", 4]
                            ]), {}, class: "form-control" %>
                </div>
                <div class="col-4">Bedroom<%= f.select :bedroom_count, options_for_select([
                                ["1 Bedroom", 1],
                                ["2 Bedrooms", 2],
                                ["3 Bedrooms", 3],
                                ["4+ Bedrooms", 4]
                            ]), {}, class: "form-control" %>
                </div>
                <div class="col-4">Bathroom<%= f.select :bathroom_count, options_for_select([
                                ["1 Bathroom", 1],
                                ["2 Bathrooms", 2],
                                ["3 Bathrooms", 3],
                                ["4+ Bathrooms", 4]
                            ]), {}, class: "form-control" %>
                </div>
            </div>
            <%= f.submit "Create my room", class: "btn btn-block btn-success mt-3"%>
        <% end %>
    </div>

</div>

app/views/listings/photo.html.erb
<div class="row">
    <div class="col-3">
        <%= render 'sidebar' %>
    </div>

    <div class="col-9">
        <div class="card">
            <div class="card-header">
                Upload Photos
            </div>
            <div class="card-body">

                <%= form_for @listing, url: listing_images_path(@listing), method: "post", html: { :multipart => true }, enctype: 'multipart/form-data' do |f| %>
                        <%= file_field_tag "images[]", type: :file, multiple: true, required: true, accept: "image/jpeg,image/gif,image/png" %>
                            <% @images.each do |image| %>
                            <div class="col col-lg-4">
                                <div class="card mt-4">
                                    <div class="card-img-top-preview"> 
                                        <%= image_tag image.image, class: "img mw-100" %>
                                    </div>
                                    <div class="card-text">
                                        <%= link_to raw("<i class=' fa fa-trash text-danger'></i>&nbsp;Delete image"), listing_image_path(@listing, image), method: :delete, class: "float-right mr-3 my-3 text-danger MontserratFont" %>
                                    </div>
                                </div>                            
                            </div>
                        <% end %>
                        <%= f.submit "Save", class: "btn btn-block btn-success mt-3"%>
                <% end %>
            </div>
        </div>
    </div>

</div>

app/views/listings/price.html.erb
<div class="row">
    <div class="col-3">
        <%= render 'sidebar' %>
    </div>

    <div class="col-9">
        <div class="card">
            <div class="card-header">
                Price
            </div>
            <div class="card-body">
                <%= form_for(@listing) do |f| %>
                    <%= f.label :price, "Price" %><%= f.number_field :price, step: 0.5, class: "form-control", placeholder: "Ex : 100.00" %>
                        
                    <%= f.submit "Save", class: "btn btn-block btn-success mt-3"%>
                <% end %>
            </div>
        </div>
    </div>

</div>

app/views/listings/show.html.erb
<div class="row">
    <div class="col-12">
        <div class="jumbotron">
            <% if @listing.images.present? %>
                <%= image_tag @listing.images.first.image, style: "width: 100px; height: 100px;" %>
                <%= link_to raw("<i class='fas fa-edit'></i> Edit"), listing_listing_path(@listing), class: "btn btn-outline-primary mr-3" %>
                <%= link_to raw("<i class='fas fa-trash-alt'></i> Delete <i class='fas fa-poo fa-rotate-90'></i>"), listing_path(@listing),method: :delete,data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger mr-3" %>
            <% else %>
                <p>No image uploaded !!</p>
            <% end %>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-7">
        <div class="jumbotron">
            
                <div class="row">
                    <h1><%= @listing.listing_name %></h1>
                    <p>Hosted by  </p>
                    <p>Reviews :</p>
                    
                </div>

                <hr>

                <div class="row text-center">
                    <div class="col-3">
                        <i class="fas fa-house-user fa-5x"></i><br><%= @listing.home_type %>
                    </div>
                    <div class="col-3">
                        <i class="fas fa-kiss-beam fa-5x"></i><br><%= @listing.accomodate %> Guests
                    </div>
                    <div class="col-3">
                        <i class="fas fa-bath fa-5x"></i><br><%= @listing.bathroom_count %> Bathrooms
                    </div>
                    <div class="col-3">
                        <i class="fas fa-bed fa-5x"></i><br><%= @listing.bedroom_count %> Bedrooms
                    </div>
                </div>

                <hr>

                <div class="row text-center">
                    <p><h3>About This Listing</h3> <br/>
                    <%= @listing.listing_description %> </p>
                <hr>                    
                </div>
                
                <div class="row text-center">
                    <h3>Amenities</h3>
                    <table class="table table-borderless">
                        <tbody>
                            <tr>
                                <td><%= is_filled?(@listing.has_internet) %> Internet</td>
                                <td><%= is_filled?(@listing.has_kitchen) %> Kitchen</td>
                                <td><%= is_filled?(@listing.has_tv) %> TV</td>
                            </tr>
                            <tr>
                                <td><%= is_filled?(@listing.has_heating) %> Heating</td>
                                <td><%= is_filled?(@listing.has_air_conditioner) %> Air conditioner</td>
                            </tr>
                        </tbody>
                    </table>
                    <hr>
                </div>

            <div class="row">
                <div class="col-12">
                <% if @listing.images.present? %>
                    <div class="carousel slide" data-ride="carousel" id="carousel-1">
                        <div class="carousel-inner" role="listbox">
                            <% @listing.images.each do |images| %>
                                <div class="carousel-item <%= images.id == @listing.images.first.id ? 'active' : '' %>">
                                    <%= image_tag images.image, class: "mw-100 d-block gallery" ,style: "width: 700px; height: 400px" %>
                                </div>
                            <% end %>
                        </div>
                    </div>

                    <div class="div">
                        <button class="carousel-control-prev" role="button" href="#carousel-1" data-slide="prev">
                            <span class="carousel-control-prev-icon"></span><span class="sr-only">Previous</span>
                        </button>
                        <button class="carousel-control-next" role="button" href="#carousel-1" data-slide="next">
                            <span class="carousel-control-next-icon"></span><span class="sr-only">Next</span>
                        </button>
                    </div>

                    <ol class="carousel-indicators">
                        <% @listing.images.each do |listing| %>
                            <li date-target="#carousel-1" date-slide-to="<% listing.id %>" class="active"></li>
                        <% end %>
                    </ol>

                <% else %>
                    <p>No Images Found</p>
                <% end %>
                </div>
            </div>

            <div class="row text-center">
                <h3>Location</h3>
                <hr>
                <div id="map"></div>
            </div>

            <div class="row text-center">
                <h3>Reviews</h3>
                
            </div>

        </div>
    </div>


    
<% if @listing.users_id != current_user.id %>
  <div class="col-5">
        <%= form_for [@listing, @listing.bookings.new] do |f| %>
            <div class="jumbotron">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title"><p>$ <%= @listing.price %> Per Night</p></h5>
                            
                        <div class="col-12">
                            <div class="row">
                                <div class="col-6">Check In<br>
                                    <%= f.hidden_field :listing_id, value: @listing.id %>
                                    <%= f.text_field :check_in_date, id: "check_in_date", class: "form-control", readonly: true, placeholder: "Check In Date" %>
                                </div>
                                <div class="col-6">Check Out<br>
                                    <%= f.text_field :check_out_date, id: "check_out_date", class: "form-control", readonly: true, placeholder: "Check Out Date"%>
                                </div>
                                <div class="col-12">
                                    <div id="preview" style="display: none;" >
                                        <div class="row">
                                            <p class="text-center" id="message"></p>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <p class="text-center">PRICE</p>
                                            </div>
                                            <div class="col">
                                                <p class="text-center">$<%= @listing.price %></p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <p class="text-center">Night(s)</p>
                                            </div>
                                            <div class="col">
                                                <p class="text-center">x <span id="nights"></span> </p>
                                            </div>
                                        </div>
                                        <hr/>
                                        <div class="row">
                                            <div class="col">
                                                <h4 class="text-center">TOTAL</h4>
                                            </div>
                                            <div class="col">
                                                <p class="text-center">$ <span id="total_price"></span></p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-12 mt-3">
                                    <%= f.submit "RESERVE", id: 'reserve', class: "btn btn-success " %>
                                </div>
                            </div>   
                        </div>           
                    </div>
                </div>
            </div>
        <% end %>
    </div>
    <% end %>
</div>


  <script>
    $(function(){
        $("#check_in_date").datepicker({
            autoclose: true,
            todayHighlight: true,
            toggleActive: true,
            format: 'dd/mm/yyyy',
            startDate: '0',
            endDate: '+3m',
        }).on('changeDate', function(selected){
        updateDate($(this).find('check_out_date'), selected);
        });

        $("#check_out_date").datepicker({
            autoclose: true,
            todayHighlight: true,
            toggleActive: true,
            format: 'dd/mm/yyyy',
            endDate: '+3m',
        }).on('changeDate', function(selected){
        updateDate($(this).find('check_in_date'), selected);
        });

        function updateDate(inputs, selected){
            var minDate = new Date(selected.date.valueOf());
            $('#check_out_date').datepicker('setStartDate', minDate);
            $('#check_in_date').datepicker('setEndDate', minDate);
            unavailableDates = [];

            $.ajax({
                url: '<%= check_current_bookings_listing_path(@listing) %>',
                dataType: 'json',
                success: function(data){
                    console.log("Success");
                    $.each(data, function(arrayID, arrayValue) {
                    for(var i = new Date(arrayValue.check_in_date); i <= new Date(arrayValue.check_out_date); i.setDate(i.getDate()+1)){
                        unavailableDates.push($.datepicker.formatDate('d-m-yy', i));
                        }
                    })
                    console.log(unavailableDates)
                }
            })
            console.log($('#check_in_date').datepicker("getDate"));
            console.log($('#check_out_date').datepicker("getDate"));
            var check_in = $('#check_in_date').datepicker("getDate");
            var check_out = $('#check_out_date').datepicker("getDate");
            var nights = (check_out - check_in)/1000/3600/24;
            var input = {
                'check_in_date': check_in,
                'check_out_date': check_out
            }
            $.ajax({
                url: '<%= review_booking_listing_path(@listing) %>',
                data: input,
                success: function(data){
                    if(data.conflict){
                        $('#message').text('Selected Dates are Unavailable');
                        $('#preview').hide();
                        $('#reserve').attr('disabled', true)
                    } else {
                        $('#message').text('Selected Dates are Available');
                        $('#preview').show();
                        $('#reserve').attr('disabled', false)
                        if(check_in.getTime() == check_out.getTime()){
                            nights = 1;
                        }
                    }
                    var total_price = nights * <%= @listing.price %>
                    $('#nights').text(nights);
                    $('#total_price').text(total_price);
                }
            })
        }
    });
  </script>


<script src="https://maps.googleapis.com/maps/api/js?key=[AIzaSyBbAhu9_5HdaJJi7sB5RvXy-5pY3i3DLNI]"></script>