config/routes.rb
Rails.application.routes.draw do

  resources :listings do
    resources :images, only: [:create, :destroy]
    resources :bookings
    member do
      get 'listing'
      get 'price'
      get 'description'
      get 'photo'
      get 'amenity'
      get 'location'
      get 'check_current_bookings'
      get 'review_booking'
    end
  end

  
  get 'users/show'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users, only: [:show]

  get 'static_page/index'
  get 'search' => 'searches#search'

  root  'static_pages#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <div class="container">
        <a class="navbar-brand" href="/">Airbnb-clone</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
            
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <form class="form-inline my-2 my-lg-0" action="search.html.erb">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </ul>
            
            <ul class="navbar-nav ml-auto">
            <%= link_to "Become a host", new_listing_path, class: "btn btn-outline-primary mr-3" %>
                <% if user_signed_in? %>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false"><%=current_user.name %></a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to "Profile" , user_path(current_user) ,class: "dropdown-item" %>
                    <div class="dropdown-divider"></div>
                    <%= link_to "Manage Listings", listings_path, class: "dropdown-item" %>
                    <%= link_to "Your Reservation" , "" ,class: "dropdown-item" %>
                    <%= link_to "Go Trip" , "" ,class: "dropdown-item" %>
                    <div class="dropdown-divider"></div>
                    <%= link_to raw("<i class='fa fa-sign-out-alt'></i> Logout"), destroy_user_session_path, class: "dropdown-item", method: :delete %>
                    </div>
                </li>
                <% else %>
                    <li class="nav-item active">
                        <%= link_to "Log in" , new_user_session_path ,class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Sign up" , new_user_registration_url ,class: "nav-link"%>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= yield(:title) %> |Airbnb-clone</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <%=
        flash_messages = [] 
            flash.each do |type, message| 
                type = 'success' if type == 'notice' 
                type = 'error'   if type == 'alert' 
                text = "<script>toastr.#{type}('#{message}','', 
                {
                'closeButton': true,
                'debug': false,
                'newestOnTop': false,
                'progressBar': false,
                'positionClass': 'toast-bottom-right',
                'preventDuplicates': false,
                'onclick': null,
                'showDuration': '3000',
                'hideDuration': '3000',
                'timeOut': '5000',
                'extendedTimeOut': '1000',
                'showEasing': 'swing',
                'hideEasing': 'linear',
                'showMethod': 'fadeIn',
                'hideMethod': 'fadeOut'
                });  </script>"
            flash_messages << text.html_safe if message 
            end 
            flash_messages.join("\n").html_safe            
        %>
        <%= render "layouts/header" %>
        <div class="container mt-4">
            <%= yield %>
        </div>
    </body>
</html>